# Generated by Django 4.2.7 on 2024-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0002_alter_userprofile_address_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
