# Generated by Django 4.2.7 on 2024-02-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0003_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap_app.category'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
